config/routes.rb
Rails.application.routes.draw do
  get 'word_of_the_week_reactions/new'

  root to: 'static_pages#home'

  ### users ###
  devise_for :users, controllers: { registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show, :index, :destroy]

  get '/users/:id/make_admin', to: 'users#make_admin', as: 'make_admin'
  get '/leaderboard', to: 'users#leaderboard', as: 'leaderboard'
  get '/leaderboard_normal_questions', to: 'users#leaderboard_normal_questions', as: 'leaderboard_normal_questions'
  get '/leaderboard_choose_image', to: 'users#leaderboard_choose_image', as: 'leaderboard_choose_image'
  get '/leaderboard_write_word', to: 'users#leaderboard_write_word', as: 'leaderboard_write_word'
  get '/invites', to: 'users#invites', as: 'invites'

  ### questions ###
  get 'questions/new_choose_image', to: 'questions#new_choose_image', as: 'new_choose_image'
  get 'questions/new_write_word', to: 'questions#new_write_word', as: 'new_write_word'
  resources :questions
  get 'questions/unchecked_questions', path: '/unchecked_questions'
  get 'questions/:id/submit_answer', to: 'questions#submit_answer', as: 'submit_answer'
  get 'questions/:id/approve_question', to: 'questions#approve_question', as: 'approve'
  get 'questions/:id/show_check', to: 'questions#show_check', as: 'show_check'

  ### static_pages ###
  get 'static_pages/pick_category'
  get 'static_pages/pick_language'
  get 'static_pages/choose_game'

  ### word of the week ###
  resources :word_of_the_weeks, only: [:index, :edit, :update, :show]
  resources :word_of_the_week_reactions, only: [:new, :create]

  ### teams ###
  resources :teams, except: [:destroy] do
    resources :memberships, only: [:create, :new]
  end

  get 'memberships/:id/accept_membership', to: 'memberships#accept_membership', as: 'accept_membership'
  get 'memberships/:id/deny_membership', to: 'memberships#deny_membership', as: 'deny_membership'
  resources :memberships, only: [:destroy]
end

app/models/question.rb
class Question < ActiveRecord::Base
  ### CALLBACKS ###
  before_create :question_defaults

  ### RELATIONS ###
  belongs_to :user
  belongs_to :category
  belongs_to :language
  has_many :answers, dependent: :destroy

  ### DELEGATE ###
  delegate :title, to: :category, prefix: true
  delegate :title, to: :language, prefix: true

  ### CALLBACKS ###
  after_create :set_correct_answer

  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  ### VALIDATIONS ###
  validates :category_id, presence: true
  validates :language_id, presence: true
  validate :add_least_one_is_present
  validate :require_two_answers

  def question_defaults
    self.approved = 0
  end

  def set_correct_answer
    update_attributes(correct_answer_id: answers.first.id)
    save
  end

  ### UPLOADER ###
  mount_uploader :image, ImageUploader

  ### METHODS ###
  def user_points
    user.points = user.points + 10
    user.save
  end

  def self.get_back_one_random_question(val)
    where(val, approved: true).offset(rand(Question.where(val, approved: true).count)).first
  end

  private

  def add_least_one_is_present
    if category_id != 3
      if title.blank?
        errors.add(:base, 'Voeg op zijn minst een afbeelding en title toe!')
      end
    elsif image.blank?
      errors.add(:base, 'Voeg een afbeelding toe!')
    end
  end

  def require_two_answers
    if category_id != 3
      errors.add(:base, 'Geef minstens twee antwoorden') if answers.size < 2
    elsif answers.size == 0
      errors.add(:base, 'Geef het woord dat bij de afbeelding hoort')
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :approve_question, :submit_answer, :show_check, :edit, :update, :destroy]
  before_action :set_new_question, only: [:new, :new_write_word, :new_choose_image]
  before_action :check_admin, only: [:unchecked_questions, :show_check, :approve_question, :index]

  def show
    get_questions = Question.where.not(id: @question.id).where(approved: true)
    @question_random = get_questions.offset(rand(get_questions.count)).first
  end

  def new
  end

  def new_write_word
  end

  def new_choose_image
  end

  def index
    @questions = Question.where(approved: true)
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to root_path, notice: 'Vraag aangemaakt'
    elsif @question.category_id == 1
      render 'new', notice: 'Vraag aanmaak mislukt'
    elsif @question.category_id == 2
      render 'new_choose_image', notice: 'Vraag aanmaak mislukt'
    else
      render 'new_write_word', notice: 'Vraag aanmaak mislukt'
    end
  end

  def unchecked_questions
    @questions = Question.where(approved: false)
  end

  def show_check
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to show_check_path(@question), notice: 'Vraag is aangepast'
    else
      render 'edit', notice: 'Aanpassen mislukt'
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_unchecked_questions_path, notice: 'Vraag is verwijdert'
  end

  def approve_question
    @question.approved = true
    @question.user_points
    if @question.save
      redirect_to questions_unchecked_questions_path
    end
  end

  def submit_answer
    answer = Answer.find(params[:answer_id])
    if answer.id == @question.correct_answer_id
      current_user.points = current_user.points + 2
      current_user.memberships.where(accepted: true).each do |m|
        m.points = m.points + 1
        m.save
      end
      current_user.save
      UserResult.create(user: current_user, category: @question.category,
                        language: @question.language, correctly_answered: true)
    else
      UserResult.create(user: current_user, category: @question.category,
                        language: @question.language, correctly_answered: false)
    end

    render json: @question
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def set_new_question
    @question = Question.new
  end

  def question_params
    params.require(:question).permit(:title, :image,
                                     :image_cache, :language_id,
                                     :category_id, answers_attributes: [:id, :title,
                                                                        :image, :image_cache,
                                                                        :_destroy])
  end

  def check_admin
    redirect_to root_path, notice: 'Je hebt hier niet genoeg rechten voor!' unless current_user.admin
  end
end

app/views/questions/_choose_image_form.html.erb
<fieldset>
	<%= error_messages_for question %>

	<%= nested_form_for question, html: { :multipart => true } do |f| %>
		<div class='field'>
			<%= f.label :title, 'Woord van de afbeelding' %>
			<%= f.text_field :title, placeholder: 'Vul de vraag in!' %>
		</div>
		<div class='field'>
			<%= f.label :language, 'Taalkeuze' %>
			<%= f.collection_select(:language_id, Language.all, :id, :title) %>
		</div>
		<%= f.hidden_field :category_id, value: 2 %>

		<%= f.fields_for :answers do |answer| %>
			<% if action_name == 'edit' %>
				<div class="imagePreviewFill" data-image-0='<%= question.answers.first.image.url(:image_cropped) %>' data-image-1='<%= question.answers.last.image.url(:image_cropped) %>'></div>
			<% end %>
			<div class='answerfield'>
	      <%= f.label :answer, 'Kies een afbeelding' %>
	      <div class="imagePreview">
	      </div>
				<%= answer.file_field :image, class: 'imageUploadAnswer' %>
				<%= answer.hidden_field :image_cache %>
			</div>
		<% end %>
		<p><%= f.link_to_add "Afbeelding toevoegen!", :answers, class: 'jsTriggerAnswers', data_trigger_times: '2' %></p>
		
		<div class='actions'>
			<%= f.submit 'Versturen', data: { disable_with: 'Aan het versturen...' } %>
		</div>
	<% end %>
</fieldset>

app/views/questions/_form.html.erb
<fieldset>
	<%= error_messages_for question %>

	<%= nested_form_for question, html: { :multipart => true } do |f| %>
		<div class='field'>
			<%= f.label :image, 'Voeg een afbeelding toe!' %>
			<div class="imagePreview">
				<% if question.image? %>
	        <%= image_tag question.image.url(:thumb), class: 'image-preview' %>
	      <% end %>
      </div>
			<%= f.file_field :image, class: 'imageUpload' %>
			<%= f.hidden_field :image_cache %>
		</div>
		<div class='field'>
			<%= f.label :title, 'Vul een vraag in!' %>
			<%= f.text_field :title, placeholder: 'Vul de vraag in!' %>
		</div>
		<div class='field'>
			<%= f.label :language, 'Taalkeuze' %>
			<%= f.collection_select(:language_id, Language.all, :id, :title) %>
		</div>
		<%= f.hidden_field :category_id, value: 1 %>
		<%= f.label :answer, 'Antwoorden' %>
		<%= f.fields_for :answers do |answer| %>
			<div class='answerfield'>
				<%= answer.text_field :title, placeholder: 'Voeg een antwoord toe!' %>
			</div>
		<% end %>
		<p><%= f.link_to_add "Antwoord toevoegen!", :answers, class: 'jsTriggerAnswers', data_trigger_times: '4' %></p>
		
		<div class='actions'>
			<%= f.submit 'Versturen', data: { disable_with: 'Aan het versturen...' }, class: 'btn new' %>
		</div>
	<% end %>
</fieldset>

app/views/questions/_question_type.html.erb
<h2>Nieuwe vraag toevoegen!</h2>

<div class='question-types clearfix'>
	<div class='type one' >
		<div>
			<div class='content'>
				<div>
					<%= link_to 'Question type: 1 Normale vraag', new_question_path %>
				</div>
			</div>
		</div>
	</div>
	<div class='type two' >
		<div>
			<div class='content'>
				<div>
					<%= link_to 'Question type: 2 Kies tussen twee afbeeldingen', new_choose_image_path %>
					</div>
			</div>
		</div>
	</div>
	<div class='type three' >
		<div>
			<div class='content'>
				<div>
					<%= link_to 'Question type: 3 Afbeelding en schrijf het woord', new_write_word_path %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/questions/_write_word_form.html.erb
<fieldset>
	<%= error_messages_for question %>

	<%= nested_form_for question, html: { :multipart => true } do |f| %>
		<div class='field'>
			<%= f.label :image, 'Voeg een afbeelding toe!' %>
			<div class="imagePreview">
				<% if question.image? %>
	        <%= image_tag question.image.url(:thumb), class: 'image-preview' %>
	      <% end %>
      </div>
			<%= f.file_field :image, class: 'imageUpload' %>
			<%= f.hidden_field :image_cache %>
		</div>
		<div class='field'>
			<%= f.label :language, 'Taalkeuze' %>
			<%= f.collection_select(:language_id, Language.all, :id, :title) %>
		</div>
		<%= f.hidden_field :category_id, value: 3 %>

		<%= f.label :answer, 'Antwoord' %>
		<%= f.fields_for :answers do |answer| %>
			<div class='answerfield'>
				<%= answer.text_field :title, placeholder: 'Voeg een antwoord toe!' %>
			</div>
		<% end %>
		<p><%= f.link_to_add "Antwoord toevoegen!", :answers, class: 'jsTriggerAnswers', data_trigger_times: '1' %></p>
		
		<div class='actions'>
			<%= f.submit 'Versturen', data: { disable_with: 'Aan het versturen...' } %>
		</div>
	<% end %>
</fieldset>

app/views/questions/edit.html.erb
<% if @question.category_id == 1 %>
	<%= render 'form', question: @question %>
<% elsif @question.category_id == 2 %>
	<%= render 'choose_image_form', question: @question %>
<% else %>
	<%= render 'write_word_form', question: @question %>
<% end %>

app/views/questions/index.html.erb
<h2>Vragenoverzicht</h2>
<table>
  <thead>
    <tr>
      <th>Vraag<th>
      <th>Soort vraag</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |q| %>
    <tr>
      <td>
        <%= link_to q.title, show_check_path(q) if q.category_id != 3 %><%= link_to q.answers.first.title, show_check_path(q) if q.category_id == 3 %>
      </td>
      <td></td>
      <td>
        <% if q.category_id == 1 %>
          ABCD vraag
        <% elsif q.category_id == 2 %>
          Kies een afbeelding
        <% elsif q.category_id == 3 %>
          Schrijven
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/new.html.erb
<%= render 'question_type' %>

<%= render 'form', question: @question %>

<div class='js-set-active' data-class-name='.one'></div>

app/views/questions/new_choose_image.html.erb
<%= render 'question_type' %>

<%= render 'choose_image_form', question: @question %>

<div class='js-set-active' data-class-name='.two'></div>

app/views/questions/new_write_word.html.erb
<%= render 'question_type' %>

<%= render 'write_word_form', question: @question %>

<div class='js-set-active' data-class-name='.three'></div>

app/views/questions/show.html.erb
<div class='question clearfix'>

	<h6><%= @question.category_title %></h6>

	<p class="language <%= @question.language_title.downcase %>">
		<% if @question.category_id == 3 %>
			Maak het <span><%= @question.language_title %>e</span> woord in letters
		<% elsif @question.category_id == 2 %>
			Kies de juiste <span>afbeelding</span> bij het woord
		<% else %>
      Kies het <span>Juiste</span> antwoord
    <% end %>
	</p>

	<% if @question.image? %>
		<div class='question-image'>
			<div class="timer-container">
				<div class='timer'></div>
			</div>
			<%= image_tag @question.image %>
		</div>
	<% end %>

	<% if @question.category_id == 1 %>
	<div class='normal-question'>
		<% if !@question.image? %>
		<div class="timer-container">
			<div class='timer'></div>
		</div>
		<% end %>

		<h3><%= @question.title %></h3>

		<div class='answer-container jsData' data-answer='<%= @question.answers.first.title %>' data-question-id='<%= @question.id %>' data-wrong-answer-id='<%= @question.correct_answer_id + 1 %>'>
			<% @question.answers.shuffle.each do |answer| %>
				<%= link_to answer.title, submit_answer_path(@question, answer_id: answer.id), remote: true, class: 'js-answer-trigger answer' %>
			<% end %>
		</div>
	</div>

	<% elsif @question.category_id == 2 %>
		<div class="choose-image clearfix">
			<div class="timer-container">
				<div class='timer'></div>
			</div>

			<h3><%= @question.title %></h3>

			<div class='jsData' data-question-id='<%= @question.id %>' data-wrong-answer-id='<%= @question.correct_answer_id + 1 %>' data-answer='<%= @question.answers.first.image.url(:image_cropped) %>'>
				<% @question.answers.shuffle.each do |answer| %>
				<div class="image-container">
					<div>
						<a class='js-answer-trigger' data-remote='true' href='<%= submit_answer_path(@question, answer_id: answer.id) %>'>
							<%= image_tag answer.image.url(:image_cropped) %>
						</a>
					</div>
				</div>
				<% end %>
			</div>
		</div>


	<% elsif @question.category_id == 3 %>

		<div class='write-word jsData' data-question-id='<%= @question.id %>' data-answer='<%= @question.answers.first.title %>'>

				<div data-answer-id='<%= @question.answers.first.id %>' class='js-write-word dots-container clearfix'></div>

			<div class='js-set-letters letters clearfix'></div>

		</div>

		<%= link_to 'Bevestig antwoord', submit_answer_path(@question, answer_id: 1), remote: true, class: 'js-answer-trigger answer' %>

	<% end %>

	<div class='question-popup'>
		<p></p>
		<%= link_to 'Volgende', @question_random, class: 'btn-default next' %>
		<%= link_to 'Stoppen', root_path, class: 'btn-default quit' %>
	</div>

	<div class="overlay-popup"></div>

</div>

app/views/questions/show_check.html.erb
<div class='question clearfix'>

  <h6><%= @question.category_title %></h6>

  <p class="language <%= @question.language_title.downcase %>">
    <% if @question.category_id == 3 %>
      Maak het <span><%= @question.language_title %>e</span> woord in letters
    <% elsif @question.category_id == 2 %>
      Kies de juiste <span>afbeelding</span> bij het woord
    <% else %>
      Kies het <span>Juiste</span> antwoord
    <% end %>
  </p>

  <% if @question.image? %>
    <div class='question-image'>
      <%= image_tag @question.image %>
    </div>
  <% end %>

  <% if @question.category_id == 1 %>
    <div class='normal-question'>

      <h3><%= @question.title %></h3>

      <% @question.answers.each_with_index do |answer, index| %>
        <div class= 'answer <%= 'correct_answer' if index == 0 %> <%= 'wrong_answer' if index != 0 %>'><%= answer.title %></div>
      <% end %>
    </div>

  <% elsif @question.category_id == 2 %>
    <div class="choose-image clearfix">

      <h3><%= @question.title %></h3>

      <div>
        <% @question.answers.each_with_index do |answer, index| %>
        <div class="image-container">
          <div>
            <%= image_tag answer.image.url(:image_cropped), class: 'wrong_answer' if index != 0 %>
            <%= image_tag answer.image.url(:image_cropped), class: 'correct_answer' if index == 0 %>
          </div>
        </div>
        <% end %>
      </div>
    </div>


  <% elsif @question.category_id == 3 %>

    <div class='write-word'>

      <div class='check-letters clearfix'>
        <ul class="clearfix">
        <% @question.answers.first.title.chars.each do |c| %>
          <li>
            <%= c %>
          </li>
        <% end %>
      </div>

    </div>

  <% end %>
</div>

<ul class="btn-container">
  <% if @question.approved != true %>
    <li>
      <%= link_to 'Goedkeuren', approve_path(@question), class: 'btn-default correct' %>
    </li>
  <% end %>
  <li>
    <%= link_to 'Aanpassen', edit_question_path(@question), class: 'btn-default edit' %>
  </li>
  <li>
    <%= link_to 'Verwijderen', @question, method: :delete, data: { confirm: 'Weet je het zeker?' }, class: 'btn-default delete' %>
  </li>
</ul>

app/views/questions/unchecked_questions.html.erb
<h2>Ongecheckte vragen</h2>
<ul>
	<% @questions.each do |q| %>
		<li><%= link_to q.title, show_check_path(q) if q.category_id != 3 %></li>
    <li><%= link_to q.answers.first.title, show_check_path(q) if q.category_id == 3 %></li>
	<% end %>
</ul>