config/routes.rb
Rails.application.routes.draw do
  get 'word_of_the_week_reactions/new'

  root to: 'static_pages#home'

  ### users ###
  devise_for :users, controllers: { registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show, :index, :destroy]

  get '/users/:id/make_admin', to: 'users#make_admin', as: 'make_admin'
  get '/leaderboard', to: 'users#leaderboard', as: 'leaderboard'
  get '/leaderboard_normal_questions', to: 'users#leaderboard_normal_questions', as: 'leaderboard_normal_questions'
  get '/leaderboard_choose_image', to: 'users#leaderboard_choose_image', as: 'leaderboard_choose_image'
  get '/leaderboard_write_word', to: 'users#leaderboard_write_word', as: 'leaderboard_write_word'
  get '/invites', to: 'users#invites', as: 'invites'

  ### questions ###
  get 'questions/new_choose_image', to: 'questions#new_choose_image', as: 'new_choose_image'
  get 'questions/new_write_word', to: 'questions#new_write_word', as: 'new_write_word'
  resources :questions
  get 'questions/unchecked_questions', path: '/unchecked_questions'
  get 'questions/:id/submit_answer', to: 'questions#submit_answer', as: 'submit_answer'
  get 'questions/:id/approve_question', to: 'questions#approve_question', as: 'approve'
  get 'questions/:id/show_check', to: 'questions#show_check', as: 'show_check'

  ### static_pages ###
  get 'static_pages/pick_category'
  get 'static_pages/pick_language'
  get 'static_pages/choose_game'

  ### word of the week ###
  resources :word_of_the_weeks, only: [:index, :edit, :update, :show]
  resources :word_of_the_week_reactions, only: [:new, :create]

  ### teams ###
  resources :teams, except: [:destroy] do
    resources :memberships, only: [:create, :new]
  end

  get 'memberships/:id/accept_membership', to: 'memberships#accept_membership', as: 'accept_membership'
  get 'memberships/:id/deny_membership', to: 'memberships#deny_membership', as: 'deny_membership'
  resources :memberships, only: [:destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @teams = current_user.teams
    @word_of_this_week = WordOfTheWeek.this_week

    @frysk_score = current_user.get_back_all(1)
    @english_score = current_user.get_back_all(2)
    @dutch_score = current_user.get_back_all(3)
  end

  def pick_category
    @reading = Question.get_back_one_random_question(category_id: 1)
    @foto_quiz = Question.get_back_one_random_question(category_id: 2)
    @writing = Question.get_back_one_random_question(category_id: 3)
  end

  def pick_language
    @dutch = Question.get_back_one_random_question(language: 3)
    @english = Question.get_back_one_random_question(language: 2)
    @frisian = Question.get_back_one_random_question(language: 1)
  end

  def choose_game
    get_questions = Question.where(approved: true)
    @question = get_questions.offset(rand(get_questions.count)).first
  end
end

app/views/static_pages/choose_game.html.erb
<h2 class='title'>Kies een categorie</h2>

<div class="clearfix">
	<%= link_to 'Willekeurige vraag', @question, class: 'btn-home icon play' %>
	<%= link_to 'Categorie kiezen', static_pages_pick_category_path, class: 'btn-home icon play' %>
	<%= link_to 'Taal kiezen', static_pages_pick_language_path, class: 'btn-home icon icon play' %>
</div>

app/views/static_pages/home.html.erb
<%= render 'shared/profile_overview', user: current_user, frysk_score: @frysk_score, english_score: @english_score, dutch_score: @dutch_score %>

<div class="clearfix">
	<%= link_to 'Vraag toevoegen', new_question_path, class: 'btn-home icon add-question' %>
	<% if Question.where(approved: true).any? %>
	  <%= link_to 'Spel spelen', static_pages_choose_game_path, class: 'btn-home icon icon play' %>
	<% end %>

	<%= link_to 'Mijn profiel', current_user, class: 'btn-home icon profile' %>

	<%= link_to 'Klassement', leaderboard_path, class: 'btn-home icon leaderboard' %>
</div>

<%= link_to @word_of_this_week, class: 'margin-fix' do %>
	<%= render 'shared/word_of_the_week', word_of_the_week: @word_of_this_week %>
<% end %>

app/views/static_pages/pick_category.html.erb
<h2 class="title">Kies een categorie</h2>

<div class="clearfix">
  <%= link_to @reading.category.title, @reading, class: 'btn-home icon play' if !@reading.nil? %>
  <%= link_to @foto_quiz.category.title, @foto_quiz, class: 'btn-home icon play' if !@foto_quiz.nil? %>
  <%= link_to @writing.category.title, @writing, class: 'btn-home icon play' if !@writing.nil? %>
</div>

app/views/static_pages/pick_language.html.erb
<h2 class="title">Kies een taal</h2>

<div class="clearfix">
  <%= link_to 'Nederlands', @dutch, class: 'btn-home  icon play' %>
  <%= link_to 'English', @english, class: 'btn-home  icon play' %>
  <%= link_to 'Frysk', @frisian, class: 'btn-home  icon play' %>
</div>