config/routes.rb
Rails.application.routes.draw do
  get 'word_of_the_week_reactions/new'

  root to: 'static_pages#home'

  ### users ###
  devise_for :users, controllers: { registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show, :index, :destroy]

  get '/users/:id/make_admin', to: 'users#make_admin', as: 'make_admin'
  get '/leaderboard', to: 'users#leaderboard', as: 'leaderboard'
  get '/leaderboard_normal_questions', to: 'users#leaderboard_normal_questions', as: 'leaderboard_normal_questions'
  get '/leaderboard_choose_image', to: 'users#leaderboard_choose_image', as: 'leaderboard_choose_image'
  get '/leaderboard_write_word', to: 'users#leaderboard_write_word', as: 'leaderboard_write_word'
  get '/invites', to: 'users#invites', as: 'invites'

  ### questions ###
  get 'questions/new_choose_image', to: 'questions#new_choose_image', as: 'new_choose_image'
  get 'questions/new_write_word', to: 'questions#new_write_word', as: 'new_write_word'
  resources :questions
  get 'questions/unchecked_questions', path: '/unchecked_questions'
  get 'questions/:id/submit_answer', to: 'questions#submit_answer', as: 'submit_answer'
  get 'questions/:id/approve_question', to: 'questions#approve_question', as: 'approve'
  get 'questions/:id/show_check', to: 'questions#show_check', as: 'show_check'

  ### static_pages ###
  get 'static_pages/pick_category'
  get 'static_pages/pick_language'
  get 'static_pages/choose_game'

  ### word of the week ###
  resources :word_of_the_weeks, only: [:index, :edit, :update, :show]
  resources :word_of_the_week_reactions, only: [:new, :create]

  ### teams ###
  resources :teams, except: [:destroy] do
    resources :memberships, only: [:create, :new]
  end

  get 'memberships/:id/accept_membership', to: 'memberships#accept_membership', as: 'accept_membership'
  get 'memberships/:id/deny_membership', to: 'memberships#deny_membership', as: 'deny_membership'
  resources :memberships, only: [:destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable, :trackable
  devise :database_authenticatable, :registerable,
          :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  ### RELATIONS ###
  has_many :questions
  has_many :user_results, dependent: :destroy
  has_many :word_of_the_week_reactions, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships

  ### VALIDATIONS ###
  validates :name, presence: true

  ### CALLBACKS ###
  after_create :user_defaults
  before_destroy :remove_teams

  ### METHODS ###
  def remove_teams
    Team.where(user_id: id).destroy_all
  end

  def user_defaults
    self.admin = false if admin.nil?
    self.points = 0
    save
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.facebook_image_url = auth.info.image + '?type=large'
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] unless user.email?
      end
    end
  end

  def get_back_all(val)
    if user_results.where(language_id: val).any?
      ((user_results.where(language_id: val,
                           correctly_answered: true).count.to_f /
      user_results.where(language_id: val).count.to_f) * 100).round
    else
      0
    end
  end

  def self.search(*)
    where('name LIKE ?', '%#{*}%')
  end

  ## UPLOADER ##
  mount_uploader :avatar, ImageUploader
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :facebook_image_url)
  end

  def account_update_params
    params.require(:user).permit(:name, :avatar,
                                 :avatar_cache, :email,
                                 :password, :password_confirmation,
                                 :facebook_image_url)
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :make_admin, :destroy]
  before_action :check_admin, only: [:make_admin, :index, :destroy]

  def show
    @frysk_score = @user.get_back_all(1)
    @english_score = @user.get_back_all(2)
    @dutch_score = @user.get_back_all(3)
  end

  def leaderboard
    @users = User.all.order(:points).reverse
  end

  def leaderboard_normal_questions
    @users = User.all.order(:points).reverse
  end

  def leaderboard_choose_image
    @users = User.all.order(:points).reverse
  end

  def leaderboard_write_word
    @users = User.all.order(:points).reverse
  end

  def invites
    @memberships = current_user.memberships.where(accepted: nil)
  end

  def index
    @users = User.all.order(:name)
  end

  def make_admin
    @user.admin = true
    @user.save
    redirect_to users_path, notice: 'Gebruiker admin gemaakt'
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'Gebruiker verwijderd!'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def check_admin
    redirect_to root_path, notice: 'Je hebt hier niet genoeg rechten voor!' unless current_user.admin
  end
end

app/views/users/index.html.erb
<table>
  <thead>
    <tr>
      <th>Gebruikers</th>
      <th>Rol</th>
      <th>Acties</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td>
        <% if user.admin == true %>
          Admin
        <% else %>
          Gebruiker
        <% end -%>
      </td>
      <td><%= link_to 'verwijderen', user, method: :delete, data: { confirm: 'Weet je het zeker?' } %> <%= link_to 'Admin maken', make_admin_path(user), data: { confirm: 'Weet je het zeker?' } if user.admin != true %> </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/invites.html.erb
<h2>Uitnodigingen</h2>

<% @memberships.each do |m| %>
	<%= link_to m.team.name, m.team %> <%= link_to 'Accepteren', accept_membership_path(m) %> <%= link_to 'Weigeren', deny_membership_path(m) %>
<% end %>

app/views/users/leaderboard.html.erb
<h2 class="title">Algemeen Klassement</h2>

<%# render 'shared/find_user' %>

<ul class='sort'>
  <li>
    Sorteren:
  </li>
  <li>
    <%= link_to 'Normale vragen', leaderboard_normal_questions_path %>
  </li>
  <li>
    <%= link_to 'Kies de juiste afbeelding', leaderboard_choose_image_path %>
  </li>
  <li>
    <%= link_to 'Schrijf het woord', leaderboard_write_word_path %>
  </li>
</ul>

<table>
  <thead>
    <tr>
      <th>Positie</th>
      <th>Gebruiker</th>
      <th>Punten</th>
    </tr>
  </thead>
  <tbody>
  	<% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= link_to user.name, user %></td>
      <td><%= user.points %></td>
    </tr>
  	<% end %>
  </tbody>
</table>

app/views/users/leaderboard_choose_image.html.erb
<%= render 'shared/find_user' %>

<p><%= link_to 'Klassement', leaderboard_path %> | <%= link_to 'Normale vragen', leaderboard_normal_questions_path %> | Kies de juiste afbeelding | <%= link_to 'Schrijf het woord', leaderboard_write_word_path %></p>
<h2>Klassement kies de afbeelding</h2>
<table>
  <thead>
    <tr>
      <th>Positie</th>
      <th>Gebruiker</th>
      <th>Punten</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= link_to user.name, user %></td>
      <td><%= user.user_results.where(category_id: 2, correctly_answered: true).count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/leaderboard_normal_questions.html.erb
<%= render 'shared/find_user' %>

<p><%= link_to 'Klassement', leaderboard_path %>| Normale vragen | <%= link_to 'Kies de juiste afbeelding', leaderboard_choose_image_path %> | <%= link_to 'Schrijf het woord', leaderboard_normal_questions_path %></p>
<h2>Klassement normale vragen</h2>
<table>
  <thead>
    <tr>
      <th>Positie</th>
      <th>Gebruiker</th>
      <th>Punten</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= link_to user.name, user %></td>
      <td><%= user.user_results.where(category: 1, correctly_answered: true).count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/leaderboard_write_word.html.erb
<%= render 'shared/find_user' %>

<p><%= link_to 'Klassement', leaderboard_path %> | <%= link_to 'Normale vragen', leaderboard_normal_questions_path %> | <%= link_to 'Kies de juiste afbeelding', leaderboard_choose_image_path %> | Schrijf het woord</p>
<h2>Klassement schrijf het woord</h2>
<table>
  <thead>
    <tr>
      <th>Positie</th>
      <th>Gebruiker</th>
      <th>Punten</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= link_to user.name, user %></td>
      <td><%= user.user_results.where(category_id: 3, correctly_answered: true).count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<%= render 'shared/profile_overview', user: @user, frysk_score: @frysk_score, english_score: @english_score, dutch_score: @dutch_score %>