config/routes.rb
Rails.application.routes.draw do
  get 'word_of_the_week_reactions/new'

  root to: 'static_pages#home'

  ### users ###
  devise_for :users, controllers: { registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show, :index, :destroy]

  get '/users/:id/make_admin', to: 'users#make_admin', as: 'make_admin'
  get '/leaderboard', to: 'users#leaderboard', as: 'leaderboard'
  get '/leaderboard_normal_questions', to: 'users#leaderboard_normal_questions', as: 'leaderboard_normal_questions'
  get '/leaderboard_choose_image', to: 'users#leaderboard_choose_image', as: 'leaderboard_choose_image'
  get '/leaderboard_write_word', to: 'users#leaderboard_write_word', as: 'leaderboard_write_word'
  get '/invites', to: 'users#invites', as: 'invites'

  ### questions ###
  get 'questions/new_choose_image', to: 'questions#new_choose_image', as: 'new_choose_image'
  get 'questions/new_write_word', to: 'questions#new_write_word', as: 'new_write_word'
  resources :questions
  get 'questions/unchecked_questions', path: '/unchecked_questions'
  get 'questions/:id/submit_answer', to: 'questions#submit_answer', as: 'submit_answer'
  get 'questions/:id/approve_question', to: 'questions#approve_question', as: 'approve'
  get 'questions/:id/show_check', to: 'questions#show_check', as: 'show_check'

  ### static_pages ###
  get 'static_pages/pick_category'
  get 'static_pages/pick_language'
  get 'static_pages/choose_game'

  ### word of the week ###
  resources :word_of_the_weeks, only: [:index, :edit, :update, :show]
  resources :word_of_the_week_reactions, only: [:new, :create]

  ### teams ###
  resources :teams, except: [:destroy] do
    resources :memberships, only: [:create, :new]
  end

  get 'memberships/:id/accept_membership', to: 'memberships#accept_membership', as: 'accept_membership'
  get 'memberships/:id/deny_membership', to: 'memberships#deny_membership', as: 'deny_membership'
  resources :memberships, only: [:destroy]
end

app/views/shared/_find_user.html.erb
<fieldset>
	<%= form_tag(root_path, :method => "get", remote: true, class: 'jsFindUser') do %>
		<%= text_field_tag :search, params[:search], placeholder: "Gebruikers zoeken", class: 'jsSearchForm', autocomplete: "off" %>
	<% end %>

	<div class="jsFoundUsers">
	</div>
</fieldset>

app/views/shared/_menu.html.erb
<div class='hamburger'>
	<div>
		<span></span>
		<span></span>
		<span></span>
	</div>
</div>

<ul class='menu'>
<% if user_signed_in? %>	
	<li>
		<%= link_to current_user.name, current_user %>
	</li>
	<% if controller_name == 'users' && action_name == 'show' %>
		<li>
			<%= link_to 'Profiel aanpassen', edit_user_registration_path %>
		</li>
	<% end %>
	
	<li>
		<%= link_to 'Teams', teams_path %>
	</li>

	<li>
		<%= link_to invites_path do %>
		  <%= current_user.memberships.where(accepted: nil).count %> Uitnodiging(en)
		<% end %>
	</li>

	<% if current_user.admin == true %>
		<li>
			<%= link_to questions_unchecked_questions_path do %>
			  <%= Question.where(approved: false).count %> ongecheckte vragen
			<% end %>
		</li>
		<li>
			<%= link_to 'Woord van de week', word_of_the_weeks_path %>
		</li>
		<li>
			<%= link_to 'Gebruikers', users_path %>
		</li>
		<li>
			<%= link_to 'Vragenoverzicht', questions_path %>		
		</li>
	<% end %>
	<li>
		<%= link_to 'Uitloggen', destroy_user_session_path, method: :delete %>
	</li>
<% end %>	
</ul>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class='notice'><%= notice %></div>
<% end %>
<% if alert %>
  <div class='notice fail'><%= alert %></div>
<% end %>

app/views/shared/_profile_overview.html.erb
<div class="coverphoto">
	<div class='profile-overview'>
		<% if user.avatar? %>
			<div class='profile-image'>
				<%= image_tag user.avatar.url(:image_cropped) %>
			</div>
		<% elsif user.provider == 'facebook' %>
		<div class="profile-image facebook-image">
			<%= image_tag user.facebook_image_url, class: 'facebook-img' %>
		</div>
		<% else %>
		<div class='profile-image'>
			<%= user.name.chars.first || user.email.chars.first %>
		</div>
		<% end %>
		<div class='profile-info'>
			<% if user.name %>
			<h4><%= link_to user.name, edit_user_registration_path, class: 'edit-icon' %></h4>
			<h5><%= user.email %></h5>
			<% else %>
				<h4><%= link_to user.email, edit_user_registration_path, class: 'edit-icon' %></h4>
			<% end %>
		</div>

	</div>
	<div class="charts-index">
		<div class='centerdiv'>
			<%= easy_as_pie frysk_score %>
			<%= easy_as_pie english_score %>
			<%= easy_as_pie dutch_score %>
			<div class='scorenames'>
				<div class='scorename friestext'%>Fries</div>
				<div class='scorename engelstext'%>Engels</div>
				<div class='scorename nederlandstext'%>Nederlands</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_word_of_the_week.html.erb
<div class="wotw">
  <div class='title'>
  	<h4>Woord van week</h4>
  	<i><%= word_of_the_week.description %></i>
  </div>
  <ul class="clearfix">
  <% word_of_the_week.title.chars.each do |c| %>
  	<% if c.ord != 32%>
	  	<li>
	  		<%= c %>
	  	</li>
  	<% else %>
  		<li>
  		-
  		</li>
			<li class="break clearfix"></li>
  	<% end %>
  <% end %>
  </ul>
</div>